---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
data:
  nginx.conf: |
        worker_rlimit_nofile 8192;
        events {
          worker_connections  4096;
        }
        http {
            server {
                listen      8081;
                listen [::]:8081;
                location / {
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_pass http://server-uut:8080;
                }
            }
        }