---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-simple-proxy
spec:
  selector:
    matchLabels:
      app: golang-simple-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-simple-proxy
    spec:
      containers:
      - name: golang-simple-proxy
        image: dreg.armo.cloud:443/simple-golang-server:latest
        command: ["/simple_server"]
        args: ["-proxy-dest=http://server-uut:8080"]
        ports:
        - containerPort: 8081   
      imagePullSecrets:
        - name: caregcred