apiVersion: v1
kind: Service
metadata:
  name: goserver
  labels:
    app: goclientserver
    tier: server
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: goclientserver
    tier: server