---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-server-conf
data:
  nginx.conf: |
        worker_rlimit_nofile 8192;
        events {
          worker_connections  4096;
        }
        http {
            server {
                listen      8080;
                listen [::]:8080;
                root /www/data;
                location / {
                }
            }
        }