apiVersion: v1
kind: Service
metadata:
  name: cart-redis
  labels:
    app: acmefit
    service: cart-redis
spec:
  ports:
    - port: 6379
      name: redis-cart
  selector:
    app: acmefit
    service: cart-redis

