apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  labels:
    app: acmefit
    service: order-db
spec:
  ports:
    - port: 5432
      name: postgres-order
      protocol: TCP
  selector:
    app: acmefit
    service: order-db

