apiVersion: v1
kind: Service
metadata:
  name: users-redis
  labels:
    app: acmefit
    service: users-redis
spec:
  ports:
    - port: 6379
      name: redis-users
  selector:
    app: acmefit
    service: users-redis

