apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        args:
        - python /src/PythonHelloWorld.py; sleep 3600
        command:
        - /bin/sh
        - -c
        image: kaylaweb/python-hello-world@sha256:1e380e2669642a362c4e60f1859201b31c77ea6d67290f99062b4a4568802f3c