apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-server
    tier: cache
  name: redis-server
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-server
    tier: cache
  type: ClusterIP
