apiVersion: v1
kind: Pod
metadata:
  name: demoservice-client
  labels:
    app: demoservice-client
spec:
  containers:
    - name: demoservice-debian
      image: quay.io/armosec/demoservice:v1-debian
      ports:
        - containerPort: 8087
      env:
        - name: SERVER_PORT
          value: "8087"
    - name: demoservice-alpine
      image: quay.io/armosec/demoservice:v1-alpine
      ports:
        - containerPort: 8088
      env:
        - name: SERVER_PORT
          value: "8088"
    - name: demoservice-centos
      image: quay.io/armosec/demoservice:v1-centos7
      ports:
        - containerPort: 8089
      env:
        - name: SERVER_PORT
          value: "8089"
