---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-secret
  labels:
    app: demo-service-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-secret
  template:
    metadata:
      labels:
        app: demo-service-secret
    spec:
      containers:
      - name: demo-service-secret
        image: quay.io/armosec/demoservice:k8s-secret-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET
          value: /tmp
        volumeMounts:
        - name: encrypted-credentials-volume
          mountPath: /tmp
      volumes:
        - name: encrypted-credentials-volume
          secret:
            secretName: encrypted-credentials
