apiVersion: apps/v1
kind: Deployment
metadata:
  name: scality
  labels:
    app: scality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality
  template:
    metadata:
      labels:
        app: scality
    spec:
      containers:
        - image: scality/s3server:latest
          name: scality
