apiVersion: v1
kind: ConfigMap
metadata:
  name: kubescape-registry-scan
  namespace: kubescape
data:   
  registries: |-
    [
        {
            "registry": "public-registry:5000",
            "depth": 1,
            "include": [
                "nginx"
            ]
        }
    ]