kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-ingress-roles-binding
  labels:
    app: nginx-ingress-roles-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-roles
subjects:
- kind: ServiceAccount
  name: nginx-ingress
  namespace: {namespace}
